### ISSUE TITLE
Assignment 5.1

### ISSUE THREAD

**Issue by sairam-golakoti** [sairam-golakoti/housing-price-prediction#1]
- [x] Install and setup Regression code templates.
- [x] Run reference notebooks.
- [x] Setup and run production scripts with ML Flow.
- [x] Generate documentation.
- [x] Create a new release **v0.1**

**Comment by sairam-golakoti** [comment]
ML Flow run:
![image](https://github.com/sairam-golakoti/housing-price-prediction/assets/98318191/4cb27bfa-c36b-406b-a905-32c4de327d63)

**Comment by sairam-golakoti** [comment]
Documentation generated through Sphinx:
![image](https://github.com/sairam-golakoti/housing-price-prediction/assets/98318191/f0dd1aad-5ed0-493f-8e25-d1e61dad3703)

**Comment by DNg-tiger** [comment]
approved.
